on:
  pull_request:
    branches:
      - main
jobs:
  ktlint:
    name: ktlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ktlintCheck
        run: ./gradlew ktlintCheck
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run test
        run: ./gradlew test
  android:
    name: Compile Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Lint
        run: ./gradlew lint
      - name: Run assembleDebug
        run: ./gradlew :androidApp:assembleDebug
  js:
    name: Compile JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run browserWebpack
        run: ./gradlew :jsApp:browserWebpack
  ios:
    name: Compile iOS
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_12.3.app/Contents/Developer'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Xcodegen
        uses: xavierLowmiller/xcodegen-action@1.1.2
        with:
          spec: iosApp/project.yml
          version: '2.24.0'
      - name: Run xcodebuild
        run: xcodebuild -workspace iosApp/iosApp.xcodeproj/project.xcworkspace/ -scheme iosApp -destination 'name=iPhone 8' build
